"""Field definitions for MIS sections S1–S10 (Phase 3 & 4)."""

# Each field dict keys:
#   no    – Data Rules field number (1–58)
#   key   – sheet/session key ("f1"…"f58")
#   label – display label
#   type  – "number" | "int" | "select" | "textarea"
#   req   – bool
#   min   – numeric lower bound or None
#   max   – numeric upper bound or None
#   dec   – decimal places (number type) or None
#   opts  – list of choices (select type) or None
#   hint  – helper/tooltip text
#   sub   – sub-section group name
#   auto  – auto-calc expression string or None

S1_FIELDS = [
    # Thruput
    {"no":1, "key":"f1",  "label":"MS (MT)",                                              "type":"number",   "req":True,  "min":0, "max":None,  "dec":3,  "opts":None,                         "hint":"Enter Value in MT",                           "sub":"Thruput",                         "auto":None},
    {"no":2, "key":"f2",  "label":"HSD (MT)",                                             "type":"number",   "req":True,  "min":0, "max":None,  "dec":3,  "opts":None,                         "hint":"Enter Value in MT",                           "sub":"Thruput",                         "auto":None},
    {"no":3, "key":"f3",  "label":"Total (MT) incl. Other Products",                      "type":"number",   "req":True,  "min":0, "max":None,  "dec":3,  "opts":None,                         "hint":"Enter Value in MT",                           "sub":"Thruput",                         "auto":None},
    {"no":4, "key":"f4",  "label":"Thruput Target (MT)",                                  "type":"number",   "req":True,  "min":0, "max":None,  "dec":3,  "opts":None,                         "hint":"Enter Value in MT",                           "sub":"Thruput",                         "auto":None},
    # Expense / Budget
    {"no":5, "key":"f5",  "label":"MEB (Rs in Lacs)",                                     "type":"number",   "req":True,  "min":0, "max":None,  "dec":2,  "opts":None,                         "hint":"Enter Value in Lakhs",                        "sub":"Expense / Budget",                "auto":None},
    {"no":6, "key":"f6",  "label":"MEB % w.r.t Budget",                                   "type":"number",   "req":True,  "min":0, "max":100,   "dec":2,  "opts":None,                         "hint":"MEB Consumed vs Approved Budget %",           "sub":"Expense / Budget",                "auto":None},
    {"no":7, "key":"f7",  "label":"OPEX (Rs/MT)",                                         "type":"number",   "req":True,  "min":0, "max":None,  "dec":2,  "opts":None,                         "hint":"(Manpower + OpEx) / Thruput in MT",           "sub":"Expense / Budget",                "auto":None},
    {"no":8, "key":"f8",  "label":"OPEX Target (Rs/MT)",                                  "type":"number",   "req":True,  "min":0, "max":None,  "dec":2,  "opts":None,                         "hint":"Enter Target Ratio",                          "sub":"Expense / Budget",                "auto":None},
    # Solar Plant
    {"no":9, "key":"f9",  "label":"Solar Plant Capacity (KW)",                            "type":"int",      "req":True,  "min":0, "max":None,  "dec":0,  "opts":None,                         "hint":"Enter Solar Plant Capacity in KW",            "sub":"Solar Plant Data",                "auto":None},
    {"no":10,"key":"f10", "label":"Energy Generated by Solar Plant (KWH)",                "type":"int",      "req":True,  "min":0, "max":None,  "dec":0,  "opts":None,                         "hint":"Enter KWH generated by Solar Plant",          "sub":"Solar Plant Data",                "auto":None},
    {"no":11,"key":"f11", "label":"Energy Exported to Grid via Net Metering (KWH)",       "type":"int",      "req":True,  "min":0, "max":None,  "dec":0,  "opts":None,                         "hint":"Enter KWH Exported to Grid",                  "sub":"Solar Plant Data",                "auto":None},
    # Electricity
    {"no":12,"key":"f12", "label":"Electricity Expenditure (Rs in Lacs)",                 "type":"number",   "req":True,  "min":0, "max":None,  "dec":2,  "opts":None,                         "hint":"Enter Value in Lakhs",                        "sub":"Electricity Expenses & Consumption","auto":None},
    {"no":13,"key":"f13", "label":"Contract Demand (KVA)",                                "type":"int",      "req":True,  "min":0, "max":None,  "dec":0,  "opts":None,                         "hint":"Enter Contract Demand",                       "sub":"Electricity Expenses & Consumption","auto":None},
    {"no":14,"key":"f14", "label":"Demand in Current Month (KVA)",                        "type":"int",      "req":True,  "min":0, "max":None,  "dec":0,  "opts":None,                         "hint":"As per Electricity Bill",                     "sub":"Electricity Expenses & Consumption","auto":None},
    {"no":15,"key":"f15", "label":"Power Factor",                                         "type":"number",   "req":True,  "min":0, "max":0.99,  "dec":2,  "opts":None,                         "hint":"As per Electricity Bill",                     "sub":"Electricity Expenses & Consumption","auto":None},
    {"no":16,"key":"f16", "label":"Max Demand (KVA) in Last 6 Months",                   "type":"int",      "req":True,  "min":0, "max":None,  "dec":0,  "opts":None,                         "hint":"As per Electricity Bill",                     "sub":"Electricity Expenses & Consumption","auto":None},
    {"no":17,"key":"f17", "label":"KWH Consumed from SEB",                                "type":"int",      "req":True,  "min":0, "max":None,  "dec":0,  "opts":None,                         "hint":"As per Electricity Bill",                     "sub":"Electricity Expenses & Consumption","auto":None},
    {"no":18,"key":"f18", "label":"KWH Consumed from DG",                                 "type":"int",      "req":True,  "min":0, "max":None,  "dec":0,  "opts":None,                         "hint":"As per MFM / Records",                        "sub":"Electricity Expenses & Consumption","auto":None},
    {"no":19,"key":"f19", "label":"KWH Consumed from Solar",                              "type":"int",      "req":True,  "min":0, "max":None,  "dec":0,  "opts":None,                         "hint":"As per MFM / Records",                        "sub":"Electricity Expenses & Consumption","auto":None},
    {"no":20,"key":"f20", "label":"Total KWH Consumed at Location",                       "type":"int",      "req":False, "min":0, "max":None,  "dec":0,  "opts":None,                         "hint":"Auto Calculated = SEB + DG + Solar",          "sub":"Electricity Expenses & Consumption","auto":"f17+f18+f19"},
    {"no":21,"key":"f21", "label":"SEC (KWH/MT)",                                         "type":"number",   "req":False, "min":0, "max":None,  "dec":4,  "opts":None,                         "hint":"Auto Calculated = Total KWH / Total Thruput", "sub":"Electricity Expenses & Consumption","auto":"f20/f3"},
    # Inventory
    {"no":22,"key":"f22", "label":"Stock Loss Productwise (KL)",                          "type":"textarea", "req":True,  "min":None,"max":None,"dec":None,"opts":None,                        "hint":"e.g.  MS: -10,  HSD: +5,  SKO: 0",           "sub":"Inventory Monitoring & Control",  "auto":None},
    {"no":23,"key":"f23", "label":"Stock Loss Productwise (% vs Targets)",                "type":"textarea", "req":True,  "min":None,"max":None,"dec":None,"opts":None,                        "hint":"e.g.  MS: -0.03 vs 0%,  HSD: 0.05 vs 0%",   "sub":"Inventory Monitoring & Control",  "auto":None},
    {"no":24,"key":"f24", "label":"AIM Holds (Nos.)",                                     "type":"int",      "req":True,  "min":0, "max":None,  "dec":0,  "opts":None,                         "hint":"AIM Holds released for the month",            "sub":"Inventory Monitoring & Control",  "auto":None},
    {"no":25,"key":"f25", "label":"Day End Report (TAS vs Gate vs SAP) – Reviewed & Signed by LIC","type":"select","req":True,"min":None,"max":None,"dec":None,"opts":["Yes","No","Non-TAS Location"],"hint":"Select appropriate option",         "sub":"Inventory Monitoring & Control",  "auto":None},
    {"no":26,"key":"f26", "label":"Auto-Reconciliation (% of Tanks on Auto Reco)",        "type":"number",   "req":True,  "min":0, "max":100,   "dec":2,  "opts":None,                         "hint":"Auto Reco entries / Total Reco entries × 100","sub":"Inventory Monitoring & Control",  "auto":None},
    # Manpower
    {"no":27,"key":"f27", "label":"Management",                                           "type":"int",      "req":True,  "min":0, "max":25,    "dec":0,  "opts":None,                         "hint":"Enter Management Manpower",                   "sub":"Manpower",                        "auto":None},
    {"no":28,"key":"f28", "label":"Non-Management",                                       "type":"int",      "req":True,  "min":0, "max":50,    "dec":0,  "opts":None,                         "hint":"Enter Non-Management Manpower",               "sub":"Manpower",                        "auto":None},
    {"no":29,"key":"f29", "label":"Contract Engineers",                                   "type":"int",      "req":True,  "min":0, "max":10,    "dec":0,  "opts":None,                         "hint":"Enter Contract Engineers deployed",            "sub":"Manpower",                        "auto":None},
    {"no":30,"key":"f30", "label":"GATs",                                                 "type":"int",      "req":True,  "min":0, "max":20,    "dec":0,  "opts":None,                         "hint":"Enter GATs deployed",                         "sub":"Manpower",                        "auto":None},
    {"no":31,"key":"f31", "label":"TATs",                                                 "type":"int",      "req":True,  "min":0, "max":20,    "dec":0,  "opts":None,                         "hint":"Enter TATs deployed",                         "sub":"Manpower",                        "auto":None},
    {"no":32,"key":"f32", "label":"Security Guards (Nos.)",                               "type":"int",      "req":True,  "min":0, "max":50,    "dec":0,  "opts":None,                         "hint":"As per Wages paid",                           "sub":"Manpower",                        "auto":None},
    {"no":33,"key":"f33", "label":"Electricians (Nos.)",                                  "type":"int",      "req":True,  "min":0, "max":20,    "dec":0,  "opts":None,                         "hint":"Electricians + Helpers deployed",             "sub":"Manpower",                        "auto":None},
    {"no":34,"key":"f34", "label":"Contract Labour (Nos.)",                               "type":"int",      "req":True,  "min":0, "max":150,   "dec":0,  "opts":None,                         "hint":"Enter Contract Workers deployed",             "sub":"Manpower",                        "auto":None},
]

S2_FIELDS = [
    {"no":35,"key":"f35", "label":"VRU Available & Functioning",                          "type":"select",   "req":True,  "min":None,"max":None,"dec":None,"opts":["Yes","No","NA"],                 "hint":"Select appropriate option",                   "sub":"Finance & Planning",              "auto":None},
    {"no":36,"key":"f36", "label":"No. of Approved NPCB Projects",                       "type":"int",      "req":True,  "min":0, "max":None,  "dec":0,  "opts":None,                         "hint":"Whole numbers, max 2 digits",                 "sub":"Finance & Planning",              "auto":None},
    {"no":37,"key":"f37", "label":"Cumulative Value of Approved Projects (in Lacs)",     "type":"number",   "req":True,  "min":0, "max":None,  "dec":2,  "opts":None,                         "hint":"Enter Value in Lacs",                         "sub":"Finance & Planning",              "auto":None},
    {"no":38,"key":"f38", "label":"CAPEX (Lakhs)",                                        "type":"number",   "req":True,  "min":0, "max":None,  "dec":2,  "opts":None,                         "hint":"Enter Capex done in Lakhs",                   "sub":"Finance & Planning",              "auto":None},
    {"no":39,"key":"f39", "label":"Capex Target as per AOP (Lakhs)",                      "type":"number",   "req":True,  "min":0, "max":None,  "dec":2,  "opts":None,                         "hint":"Enter Capex Targets for FY",                  "sub":"Finance & Planning",              "auto":None},
    {"no":40,"key":"f40", "label":"CAPITALIZATION (Lakhs)",                               "type":"number",   "req":True,  "min":0, "max":None,  "dec":2,  "opts":None,                         "hint":"Capitalization done in the month",             "sub":"Finance & Planning",              "auto":None},
    {"no":41,"key":"f41", "label":"Capitalization Target as per AOP (Lakhs)",             "type":"number",   "req":True,  "min":0, "max":None,  "dec":2,  "opts":None,                         "hint":"Enter Capitalization Targets for FY",          "sub":"Finance & Planning",              "auto":None},
    {"no":42,"key":"f42", "label":"Scrap Value at Location (Rs in Lacs)",                 "type":"number",   "req":True,  "min":0, "max":None,  "dec":2,  "opts":None,                         "hint":"Enter Expected Scrap Value",                  "sub":"Finance & Planning",              "auto":None},
    {"no":43,"key":"f43", "label":"Physical Scrap Disposal (Rs in Lacs)",                 "type":"number",   "req":True,  "min":0, "max":None,  "dec":2,  "opts":None,                         "hint":"Scrap disposed value for the month",          "sub":"Finance & Planning",              "auto":None},
]

S3_FIELDS = [
    {"no":44,"key":"f44", "label":"Rakes Unloaded / Loaded",                              "type":"int",      "req":True,  "min":0, "max":None,  "dec":0,  "opts":None,                         "hint":"Enter total Rakes handled",                   "sub":"S&D Data",                        "auto":None},
    {"no":45,"key":"f45", "label":"Pending Railway Claims – Uploaded in Google Sheet",    "type":"select",   "req":True,  "min":None,"max":None,"dec":None,"opts":["Yes","No","NA"],                 "hint":"Select appropriate option",                   "sub":"S&D Data",                        "auto":None},
    {"no":46,"key":"f46", "label":"MDP Qty Target (KL)",                                  "type":"number",   "req":True,  "min":0, "max":None,  "dec":3,  "opts":None,                         "hint":"Enter productwise values",                    "sub":"S&D Data",                        "auto":None},
    {"no":47,"key":"f47", "label":"MDP Qty Actual (KL)",                                  "type":"number",   "req":True,  "min":0, "max":None,  "dec":3,  "opts":None,                         "hint":"Enter productwise values",                    "sub":"S&D Data",                        "auto":None},
    {"no":48,"key":"f48", "label":"OMC MDP Target (KL)",                                  "type":"number",   "req":True,  "min":0, "max":None,  "dec":3,  "opts":None,                         "hint":"Enter productwise values",                    "sub":"S&D Data",                        "auto":None},
    {"no":49,"key":"f49", "label":"OMC MDP Actual (KL)",                                  "type":"number",   "req":True,  "min":0, "max":None,  "dec":3,  "opts":None,                         "hint":"Enter productwise values",                    "sub":"S&D Data",                        "auto":None},
]

S4_FIELDS = [
    {"no":50,"key":"f50", "label":"EBP – Ethanol Blending Percentage",                    "type":"number",   "req":True,  "min":0, "max":100,   "dec":2,  "opts":None,                         "hint":"Enter EBP % for the month",                  "sub":"Biofuel Data",                    "auto":None},
    {"no":51,"key":"f51", "label":"Unblended MS Retail Sales (KL)",                       "type":"number",   "req":True,  "min":0, "max":None,  "dec":3,  "opts":None,                         "hint":"Enter value in KL",                           "sub":"Biofuel Data",                    "auto":None},
    {"no":52,"key":"f52", "label":"Biodiesel Receipt Qty (KL)",                           "type":"number",   "req":True,  "min":0, "max":None,  "dec":3,  "opts":None,                         "hint":"Enter value in KL",                           "sub":"Biofuel Data",                    "auto":None},
    {"no":53,"key":"f53", "label":"Biodiesel Blending Percentage",                        "type":"number",   "req":True,  "min":0, "max":100,   "dec":2,  "opts":None,                         "hint":"Enter Blending % for the month",              "sub":"Biofuel Data",                    "auto":None},
]

S5_FIELDS = [
    {"no":54,"key":"f54", "label":"M&I Index",                                              "type":"number",   "req":True,  "min":0, "max":100,   "dec":2,  "opts":None, "hint":"Enter M&I Index value",                "sub":"M&I Data", "auto":None},
    {"no":55,"key":"f55", "label":"PM Percentage",                                          "type":"number",   "req":True,  "min":0, "max":100,   "dec":2,  "opts":None, "hint":"Enter PM %",                           "sub":"M&I Data", "auto":None},
    {"no":56,"key":"f56", "label":"Breakdown Equipment Details",                            "type":"textarea", "req":False, "min":None,"max":None,"dec":None,"opts":None, "hint":"Enter details (max 750 chars)",         "sub":"M&I Data", "auto":None},
    {"no":57,"key":"f57", "label":"Tank Cleaned (Tank#, Product, Capacity & Date)",        "type":"textarea", "req":False, "min":None,"max":None,"dec":None,"opts":None, "hint":"Enter details (max 750 chars)",         "sub":"M&I Data", "auto":None},
    {"no":58,"key":"f58", "label":"Tank Cleaning Extensions (eFN# & date till extension)", "type":"textarea", "req":False, "min":None,"max":None,"dec":None,"opts":None, "hint":"Enter details (max 750 chars)",         "sub":"M&I Data", "auto":None},
]

S6_FIELDS = [
    # HSE Performance
    {"no":59, "key":"f59",  "label":"HSE Index vs Target",                                  "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter HSE Index as a percentage",             "sub":"HSE Performance",                 "auto":None},
    {"no":60, "key":"f60",  "label":"Water Consumed in Month (KL)",                         "type":"number",   "req":True,  "min":0,  "max":None, "dec":3,  "opts":None,                         "hint":"Enter values in KL as per Meter Reading",     "sub":"HSE Performance",                 "auto":None},
    {"no":61, "key":"f61",  "label":"SWC (KL/MT)",                                          "type":"number",   "req":False, "min":0,  "max":None, "dec":3,  "opts":None,                         "hint":"Auto Calculated = Water Consumed / Thruput",  "sub":"HSE Performance",                 "auto":"f60/f3"},
    {"no":62, "key":"f62",  "label":"No. of TT Accidents",                                  "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter TT Accidents occurred in Month",        "sub":"HSE Performance",                 "auto":None},
    {"no":63, "key":"f63",  "label":"No. of Fatalities",                                    "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter Fatalities due to accidents in month",  "sub":"HSE Performance",                 "auto":None},
    {"no":64, "key":"f64",  "label":"No. of Near Miss / UA / UC Reported",                  "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter Near Miss / UA / UC count",             "sub":"HSE Performance",                 "auto":None},
    {"no":65, "key":"f65",  "label":"No. of Permits Issued",                                "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter Permit Issued Count",                   "sub":"HSE Performance",                 "auto":None},
    {"no":66, "key":"f66",  "label":"No. of MOC's Created and Approved",                   "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter MOC approved Count",                    "sub":"HSE Performance",                 "auto":None},
    {"no":67, "key":"f67",  "label":"Pending MDSA Observations vs Total (%)",               "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Pending MDSA obs / Total obs × 100",          "sub":"HSE Performance",                 "auto":None},
    {"no":68, "key":"f68",  "label":"Pending OISD Observations vs Total (%)",               "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Pending OISD obs / Total obs × 100",          "sub":"HSE Performance",                 "auto":None},
    # Safety Compliance
    {"no":69, "key":"f69",  "label":"OISD Observations > 1 Year",                          "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Count of OISD observations older than 1 year","sub":"Safety Compliance",               "auto":None},
    {"no":70, "key":"f70",  "label":"All SOPs Generated & Re-validated (Date < 3 Years)",  "type":"select",   "req":True,  "min":None,"max":None,"dec":None,"opts":["Yes","No","NA"],                 "hint":"Select appropriate option",                   "sub":"Safety Compliance",               "auto":None},
    {"no":71, "key":"f71",  "label":"Green Belt Area (in SQM)",                             "type":"number",   "req":True,  "min":0,  "max":None, "dec":2,  "opts":None,                         "hint":"Enter Green Belt area in square metres",      "sub":"Safety Compliance",               "auto":None},
    # CCTV & Security
    {"no":72, "key":"f72",  "label":"No. of CCTV Installed",                                "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter total count of CCTV installed",         "sub":"CCTV & Security",                 "auto":None},
    {"no":73, "key":"f73",  "label":"CCTV Not Functional",                                  "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter Non-functional CCTV count",             "sub":"CCTV & Security",                 "auto":None},
    {"no":74, "key":"f74",  "label":"% CCTV Breakdown",                                     "type":"number",   "req":False, "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Auto Calculated = Not Functional / Total × 100","sub":"CCTV & Security",              "auto":"f73/f72*100"},
    {"no":75, "key":"f75",  "label":"VA Exception %",                                       "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter data as per VA portal",                 "sub":"CCTV & Security",                 "auto":None},
    # Awards
    {"no":76, "key":"f76",  "label":"Awards Received (Details)",                            "type":"textarea", "req":False, "min":None,"max":None,"dec":None,"opts":None,                        "hint":"Enter award details (max 750 chars)",          "sub":"Awards",                          "auto":None},
]

S7_FIELDS = [
    # Bay Operations
    {"no":77,  "key":"f77",  "label":"No. of Bays at Location",                             "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter total number of loading bays",          "sub":"Bay Operations",                  "auto":None},
    {"no":78,  "key":"f78",  "label":"No. of Functional Bays at Location",                  "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of functional bays",              "sub":"Bay Operations",                  "auto":None},
    {"no":79,  "key":"f79",  "label":"OLA %",                                               "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter OLA % as per IMS Reports",              "sub":"Bay Operations",                  "auto":None},
    {"no":80,  "key":"f80",  "label":"COLA %",                                              "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter COLA % as per IMS Reports",             "sub":"Bay Operations",                  "auto":None},
    {"no":81,  "key":"f81",  "label":"AUTO DC %",                                           "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter AUTO DC % as per IMS Reports",          "sub":"Bay Operations",                  "auto":None},
    {"no":82,  "key":"f82",  "label":"CAT-A %",                                             "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter CAT-A % as per IMS Reports",            "sub":"Bay Operations",                  "auto":None},
    {"no":83,  "key":"f83",  "label":"LPM",                                                 "type":"number",   "req":True,  "min":0,  "max":None, "dec":2,  "opts":None,                         "hint":"Enter LPM as per TAS Reports",                "sub":"Bay Operations",                  "auto":None},
    # TAS Performance
    {"no":84,  "key":"f84",  "label":"Operating Hours of Location",                         "type":"int",      "req":True,  "min":0,  "max":744,  "dec":0,  "opts":None,                         "hint":"Enter operating hours in month (max 744)",    "sub":"TAS Performance",                 "auto":None},
    {"no":85,  "key":"f85",  "label":"Indents Executed within Operational Hours",           "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count as per TAS Reports",              "sub":"TAS Performance",                 "auto":None},
    {"no":86,  "key":"f86",  "label":"Indents Executed beyond Operational Hours",           "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count as per TAS Reports",              "sub":"TAS Performance",                 "auto":None},
    {"no":87,  "key":"f87",  "label":"% Indents beyond Operational Hours",                  "type":"number",   "req":False, "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Auto Calculated = Beyond / (Within + Beyond) × 100","sub":"TAS Performance",           "auto":"f86*100/(f86+f85)"},
    {"no":88,  "key":"f88",  "label":"TFMS vs SAP Performance (%)",                         "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter % as per SAP Reports",                  "sub":"TAS Performance",                 "auto":None},
    {"no":89,  "key":"f89",  "label":"File Note No. & Date for TFMS–SAP Integration",      "type":"textarea", "req":False, "min":None,"max":None,"dec":None,"opts":None,                        "hint":"Enter brief details (max 750 chars)",          "sub":"TAS Performance",                 "auto":None},
    {"no":90,  "key":"f90",  "label":"First 2 Hours TT Released per Bay (Operational Bays)","type":"number",  "req":True,  "min":0,  "max":None, "dec":2,  "opts":None,                         "hint":"Enter value as per TAS Reports",              "sub":"TAS Performance",                 "auto":None},
    {"no":91,  "key":"f91",  "label":"Online Density % (Target 98%)",                       "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter % as per TAS Reports",                  "sub":"TAS Performance",                 "auto":None},
    {"no":92,  "key":"f92",  "label":"No. of PLC IO's Forced",                              "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count as per TAS Reports",              "sub":"TAS Performance",                 "auto":None},
    {"no":93,  "key":"f93",  "label":"No. of Manual Bay Allocations",                       "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count as per TAS Reports",              "sub":"TAS Performance",                 "auto":None},
    {"no":94,  "key":"f94",  "label":"No. of Sick TT Instances",                            "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count as per TAS Reports",              "sub":"TAS Performance",                 "auto":None},
    {"no":95,  "key":"f95",  "label":"No. of Cancelled TT's",                              "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count as per TAS Reports",              "sub":"TAS Performance",                 "auto":None},
    {"no":96,  "key":"f96",  "label":"No. of TT's Loaded Locally",                         "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count as per TAS Reports",              "sub":"TAS Performance",                 "auto":None},
    {"no":97,  "key":"f97",  "label":"Quantity of Local Loading (KL)",                      "type":"number",   "req":True,  "min":0,  "max":None, "dec":3,  "opts":None,                         "hint":"Enter value in KL",                           "sub":"TAS Performance",                 "auto":None},
    {"no":98,  "key":"f98",  "label":"Cycle Time R2 to R3 (Min)",                           "type":"number",   "req":True,  "min":0,  "max":None, "dec":2,  "opts":None,                         "hint":"Enter average cycle time in minutes",         "sub":"TAS Performance",                 "auto":None},
    {"no":99,  "key":"f99",  "label":"TAS Open Audit Observations vs Total (%)",            "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter % of open audit observations",          "sub":"TAS Performance",                 "auto":None},
    # System Compliance
    {"no":100, "key":"f100", "label":"BCU vs MFM Totalizer Matching",                       "type":"select",   "req":True,  "min":None,"max":None,"dec":None,"opts":["Yes","No","NA"],                "hint":"Select appropriate option",                   "sub":"System Compliance",               "auto":None},
    {"no":101, "key":"f101", "label":"No. of Instances of Unauthorized Flow",               "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter whole number count",                    "sub":"System Compliance",               "auto":None},
    {"no":102, "key":"f102", "label":"User Access as per Circular",                         "type":"select",   "req":True,  "min":None,"max":None,"dec":None,"opts":["Yes","No","NA"],                "hint":"Select appropriate option",                   "sub":"System Compliance",               "auto":None},
    {"no":103, "key":"f103", "label":"H, HH, HHH Matching with File Note",                  "type":"select",   "req":True,  "min":None,"max":None,"dec":None,"opts":["Yes","No","NA"],                "hint":"Select appropriate option",                   "sub":"System Compliance",               "auto":None},
    {"no":104, "key":"f104", "label":"TT Dip Check %",                                      "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter % as per SAP Reports",                  "sub":"System Compliance",               "auto":None},
]

S8_FIELDS = [
    {"no":105, "key":"f105", "label":"EM Locks Spare Inventory",                            "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count as per System Report",            "sub":"EM Lock Data",                    "auto":None},
    {"no":106, "key":"f106", "label":"EM Lock Spare Key Inventory",                         "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count as per System Report",            "sub":"EM Lock Data",                    "auto":None},
    {"no":107, "key":"f107", "label":"Dormant EM Locks",                                    "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count as per System Report",            "sub":"EM Lock Data",                    "auto":None},
    {"no":108, "key":"f108", "label":"Dormant Keys",                                        "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count as per System Report",            "sub":"EM Lock Data",                    "auto":None},
    {"no":109, "key":"f109", "label":"EM Lock Exception % — TT Outside RO Radius",         "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter % as per System Report",                "sub":"EM Lock Data",                    "auto":None},
]

S9_FIELDS = [
    # TT Fleet
    {"no":110, "key":"f110", "label":"Total TTs Operating at Location",                     "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter total TT count at location",            "sub":"TT Fleet",                        "auto":None},
    {"no":111, "key":"f111", "label":"EC Approved TT Numbers",                              "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter EC Approved TT count",                  "sub":"TT Fleet",                        "auto":None},
    {"no":112, "key":"f112", "label":"DCT TTs < 18 KL",                                     "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of DCT TTs below 18 KL",          "sub":"TT Fleet",                        "auto":None},
    {"no":113, "key":"f113", "label":"DCT TTs 18–24 KL",                                    "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of DCT TTs 18 KL to 24 KL",       "sub":"TT Fleet",                        "auto":None},
    {"no":114, "key":"f114", "label":"DCT TTs >= 25 KL",                                    "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of DCT TTs 25 KL and above",      "sub":"TT Fleet",                        "auto":None},
    {"no":115, "key":"f115", "label":"TPT TTs < 18 KL",                                     "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of TPT TTs below 18 KL",          "sub":"TT Fleet",                        "auto":None},
    {"no":116, "key":"f116", "label":"TPT TTs 18–24 KL",                                    "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of TPT TTs 18 KL to 24 KL",       "sub":"TT Fleet",                        "auto":None},
    {"no":117, "key":"f117", "label":"TPT TTs >= 25 KL",                                    "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of TPT TTs 25 KL and above",      "sub":"TT Fleet",                        "auto":None},
    {"no":118, "key":"f118", "label":"Bottom Loading TTs < 18 KL",                          "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of BL TTs below 18 KL",           "sub":"TT Fleet",                        "auto":None},
    {"no":119, "key":"f119", "label":"Bottom Loading TTs 18–24 KL",                         "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of BL TTs 18 KL to 24 KL",        "sub":"TT Fleet",                        "auto":None},
    {"no":120, "key":"f120", "label":"Bottom Loading TTs >= 25 KL",                         "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of BL TTs 25 KL and above",       "sub":"TT Fleet",                        "auto":None},
    {"no":121, "key":"f121", "label":"Non-Reporting TTs > 15 Days",                         "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"TTs not reporting for more than 15 days",     "sub":"TT Fleet",                        "auto":None},
    # TT Shortages & Violations
    {"no":122, "key":"f122", "label":"No. of TT Shortages Reported",                        "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter shortage case count for the month",     "sub":"TT Shortages & Violations",       "auto":None},
    {"no":123, "key":"f123", "label":"Cumulative TT Shortages for Month (KL)",              "type":"number",   "req":True,  "min":0,  "max":None, "dec":3,  "opts":None,                         "hint":"Enter cumulative shortage quantity in KL",    "sub":"TT Shortages & Violations",       "auto":None},
    {"no":124, "key":"f124", "label":"No. of Abnormal TT Shortage Cases Investigated",      "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of investigated cases",           "sub":"TT Shortages & Violations",       "auto":None},
    {"no":125, "key":"f125", "label":"No. of SCN Issued",                                   "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of SCNs issued in month",         "sub":"TT Shortages & Violations",       "auto":None},
    {"no":126, "key":"f126", "label":"No. of Actions Taken (Blacklisting / Termination)",  "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of blacklisting/termination actions","sub":"TT Shortages & Violations",    "auto":None},
    {"no":127, "key":"f127", "label":"Pending TT Conversion to BL (Nos)",                  "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of TTs pending BL conversion",   "sub":"TT Shortages & Violations",       "auto":None},
    {"no":128, "key":"f128", "label":"Speed Violation %",                                   "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter % as per System Report",                "sub":"TT Shortages & Violations",       "auto":None},
    {"no":129, "key":"f129", "label":"Route Violations %",                                  "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter % as per System Report",                "sub":"TT Shortages & Violations",       "auto":None},
    {"no":130, "key":"f130", "label":"% Routes Corrected",                                  "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter % of routes corrected in month",        "sub":"TT Shortages & Violations",       "auto":None},
    {"no":131, "key":"f131", "label":"Pending Toll Amount to be Approved (Rs)",             "type":"number",   "req":True,  "min":0,  "max":None, "dec":2,  "opts":None,                         "hint":"Enter pending toll amount in Rupees",         "sub":"TT Shortages & Violations",       "auto":None},
    {"no":132, "key":"f132", "label":"Driver Ranking Maintained",                           "type":"select",   "req":True,  "min":None,"max":None,"dec":None,"opts":["Yes","No","NA"],                "hint":"Select appropriate option",                   "sub":"TT Shortages & Violations",       "auto":None},
    {"no":133, "key":"f133", "label":"TPI Inspection Part-A",                               "type":"select",   "req":True,  "min":None,"max":None,"dec":None,"opts":["Yes","No","NA"],           "hint":"Select appropriate option",                   "sub":"TT Shortages & Violations",       "auto":None},
    {"no":134, "key":"f134", "label":"TPI Inspection Part-B",                               "type":"select",   "req":True,  "min":None,"max":None,"dec":None,"opts":["Yes","No","NA"],           "hint":"Select appropriate option",                   "sub":"TT Shortages & Violations",       "auto":None},
    {"no":135, "key":"f135", "label":"EOI Tender Finalization Status",                      "type":"textarea", "req":False, "min":None,"max":None,"dec":None,"opts":None,                        "hint":"Enter brief status details (max 750 chars)",  "sub":"TT Shortages & Violations",       "auto":None},
    {"no":136, "key":"f136", "label":"Freight Amount Recovered for Month (Rs)",             "type":"number",   "req":True,  "min":0,  "max":None, "dec":2,  "opts":None,                         "hint":"Enter amount recovered in Rupees",            "sub":"TT Shortages & Violations",       "auto":None},
    {"no":137, "key":"f137", "label":"Total TDG Violations (% of Total Trips)",             "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter TDG Violation % as per VTS Portal",    "sub":"TT Shortages & Violations",       "auto":None},
]

S10_FIELDS = [
    {"no":138, "key":"f138", "label":"Idea Submissions (Nos)",                              "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter number of ideas submitted",             "sub":"Others",                          "auto":None},
    {"no":139, "key":"f139", "label":"IRR's (if any)",                                      "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of IRRs",                         "sub":"Others",                          "auto":None},
    {"no":140, "key":"f140", "label":"Legal Cases",                                         "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of legal cases",                  "sub":"Others",                          "auto":None},
]

SECTION_FIELDS: dict[int, list] = {
    1: S1_FIELDS,
    2: S2_FIELDS,
    3: S3_FIELDS,
    4: S4_FIELDS,
    5: S5_FIELDS,
    6: S6_FIELDS,
    7: S7_FIELDS,
    8: S8_FIELDS,
    9: S9_FIELDS,
    10: S10_FIELDS,
}

SECTION_NAMES: dict[int, str] = {
    1:  "S1 — Operations",
    2:  "S2 — Finance & Planning (F&P)",
    3:  "S3 — Supply & Distribution (S&D)",
    4:  "S4 — Biofuel",
    5:  "S5 — Maintenance & Inspection (M&I)",
    6:  "S6 — Health, Safety & Environment (HSE)",
    7:  "S7 — Operational Efficiency & TAS",
    8:  "S8 — EM Lock Performance",
    9:  "S9 — Transportation",
    10: "S10 — Others",
}
