"""Field definitions for MIS sections S1–S10 (Phase 3 & 4)."""

# Each field dict keys:
#   no    – Data Rules field number (1–58)
#   key   – sheet/session key ("f1"…"f58")
#   label – display label
#   type  – "number" | "int" | "select" | "textarea"
#   req   – bool
#   min   – numeric lower bound or None
#   max   – numeric upper bound or None
#   dec   – decimal places (number type) or None
#   opts  – list of choices (select type) or None
#   hint  – helper/tooltip text
#   sub   – sub-section group name
#   auto  – auto-calc expression string or None

S1_FIELDS = [
    # Thruput
    {"no":1,   "key":"f1",   "label":"MS (MT)",                                              "type":"number",   "req":True,  "min":0, "max":None,  "dec":3,  "opts":None,                         "hint":"Enter Value in MT",                           "sub":"Thruput",                         "auto":None},
    {"no":2,   "key":"f2",   "label":"HSD (MT)",                                             "type":"number",   "req":True,  "min":0, "max":None,  "dec":3,  "opts":None,                         "hint":"Enter Value in MT",                           "sub":"Thruput",                         "auto":None},
    {"no":142, "key":"f142", "label":"ATF (MT)",                                             "type":"number",   "req":True,  "min":0, "max":None,  "dec":3,  "opts":None,                         "hint":"Enter Value in MT",                           "sub":"Thruput",                         "auto":None},
    {"no":3,   "key":"f3",   "label":"Total (MT) incl. Other Products",                      "type":"number",   "req":True,  "min":0, "max":None,  "dec":3,  "opts":None,                         "hint":"Enter Value in MT",                           "sub":"Thruput",                         "auto":None},
    {"no":4,   "key":"f4",   "label":"Thruput Target (MT)",                                  "type":"number",   "req":True,  "min":0, "max":None,  "dec":3,  "opts":None,                         "hint":"Enter Value in MT",                           "sub":"Thruput",                         "auto":None},
    # Expense / Budget
    {"no":5, "key":"f5",  "label":"MEB (Rs in Lacs)",                                     "type":"number",   "req":True,  "min":0, "max":None,  "dec":2,  "opts":None,                         "hint":"Enter Value in Lakhs",                        "sub":"Expense / Budget",                "auto":None},
    {"no":6, "key":"f6",  "label":"MEB % w.r.t Budget",                                   "type":"number",   "req":True,  "min":0, "max":100,   "dec":2,  "opts":None,                         "hint":"MEB Consumed vs Approved Budget %",           "sub":"Expense / Budget",                "auto":None},
    {"no":7, "key":"f7",  "label":"OPEX (Rs/MT)",                                         "type":"number",   "req":True,  "min":0, "max":None,  "dec":2,  "opts":None,                         "hint":"(Manpower + OpEx) / Thruput in MT",           "sub":"Expense / Budget",                "auto":None},
    {"no":8, "key":"f8",  "label":"OPEX Target (Rs/MT)",                                  "type":"number",   "req":True,  "min":0, "max":None,  "dec":2,  "opts":None,                         "hint":"Enter Target Ratio",                          "sub":"Expense / Budget",                "auto":None},
    # Solar Plant
    {"no":9, "key":"f9",  "label":"Solar Plant Capacity (KW)",                            "type":"int",      "req":True,  "min":0, "max":None,  "dec":0,  "opts":None,                         "hint":"Enter Solar Plant Capacity in KW",            "sub":"Solar Plant Data",                "auto":None},
    {"no":10,"key":"f10", "label":"Energy Generated by Solar Plant (KWH)",                "type":"int",      "req":True,  "min":0, "max":None,  "dec":0,  "opts":None,                         "hint":"Enter KWH generated by Solar Plant",          "sub":"Solar Plant Data",                "auto":None},
    {"no":11,"key":"f11", "label":"Energy Exported to Grid via Net Metering (KWH)",       "type":"int",      "req":True,  "min":0, "max":None,  "dec":0,  "opts":None,                         "hint":"Enter KWH Exported to Grid",                  "sub":"Solar Plant Data",                "auto":None},
    # Electricity
    {"no":12,"key":"f12", "label":"Electricity Expenditure (Rs in Lacs)",                 "type":"number",   "req":True,  "min":0, "max":None,  "dec":2,  "opts":None,                         "hint":"Enter Value in Lakhs",                        "sub":"Electricity Expenses & Consumption","auto":None},
    {"no":13,"key":"f13", "label":"Contract Demand (KVA)",                                "type":"int",      "req":True,  "min":0, "max":None,  "dec":0,  "opts":None,                         "hint":"Enter Contract Demand",                       "sub":"Electricity Expenses & Consumption","auto":None},
    {"no":14,"key":"f14", "label":"Demand in Current Month (KVA)",                        "type":"int",      "req":True,  "min":0, "max":None,  "dec":0,  "opts":None,                         "hint":"As per Electricity Bill",                     "sub":"Electricity Expenses & Consumption","auto":None},
    {"no":15,"key":"f15", "label":"Power Factor",                                         "type":"number",   "req":True,  "min":0, "max":0.99,  "dec":2,  "opts":None,                         "hint":"As per Electricity Bill",                     "sub":"Electricity Expenses & Consumption","auto":None},
    {"no":16,"key":"f16", "label":"Max Demand (KVA) in Last 6 Months",                   "type":"int",      "req":True,  "min":0, "max":None,  "dec":0,  "opts":None,                         "hint":"As per Electricity Bill",                     "sub":"Electricity Expenses & Consumption","auto":None},
    {"no":17,"key":"f17", "label":"KWH Consumed from SEB",                                "type":"int",      "req":True,  "min":0, "max":None,  "dec":0,  "opts":None,                         "hint":"As per Electricity Bill",                     "sub":"Electricity Expenses & Consumption","auto":None},
    {"no":18,"key":"f18", "label":"KWH Consumed from DG",                                 "type":"int",      "req":True,  "min":0, "max":None,  "dec":0,  "opts":None,                         "hint":"As per MFM / Records",                        "sub":"Electricity Expenses & Consumption","auto":None},
    {"no":19,"key":"f19", "label":"KWH Consumed from Solar",                              "type":"int",      "req":True,  "min":0, "max":None,  "dec":0,  "opts":None,                         "hint":"As per MFM / Records",                        "sub":"Electricity Expenses & Consumption","auto":None},
    {"no":20,"key":"f20", "label":"Total KWH Consumed at Location",                       "type":"int",      "req":False, "min":0, "max":None,  "dec":0,  "opts":None,                         "hint":"Auto Calculated = SEB + DG + Solar",          "sub":"Electricity Expenses & Consumption","auto":"f17+f18+f19"},
    {"no":21,"key":"f21", "label":"SEC (KWH/MT)",                                         "type":"number",   "req":False, "min":0, "max":None,  "dec":4,  "opts":None,                         "hint":"Auto Calculated = Total KWH / Total Thruput", "sub":"Electricity Expenses & Consumption","auto":"f20/f3"},
    # Inventory
    {"no":22,"key":"f22", "label":"Stock Loss Productwise (KL)",                          "type":"textarea", "req":True,  "min":None,"max":None,"dec":None,"opts":None,                        "hint":"Enter product-wise stock gain/loss for the month in KL. Use +/- signs. Format: MS: -10 KL, HSD: +5 KL, SKO: 0 KL, ATF: -2 KL. NA if no stock loss applicable.", "sub":"Inventory Monitoring & Control",  "auto":None},
    {"no":23,"key":"f23", "label":"Stock Loss Productwise (% vs Targets)",                "type":"textarea", "req":True,  "min":None,"max":None,"dec":None,"opts":None,                        "hint":"Enter stock loss % vs targets for each product. Format: MS: -0.03% vs 0% target, HSD: +0.05% vs 0% target. NA if not applicable.", "sub":"Inventory Monitoring & Control",  "auto":None},
    {"no":24, "key":"f24",  "label":"AIM Holds (Nos.)",                                    "type":"int",      "req":True,  "min":0,    "max":None,  "dec":0,    "opts":None,                              "hint":"AIM Holds released for the month",                                                    "sub":"Inventory Monitoring & Control",  "auto":None},
    {"no":143,"key":"f143","label":"Reasons for AIM Hold",                                 "type":"textarea", "req":False, "min":None, "max":None,  "dec":None, "opts":None,                              "hint":"Enter reasons for AIM Holds raised this month (max 750 chars). Leave blank if no AIM hold this month.", "sub":"Inventory Monitoring & Control",  "auto":None},
    {"no":144,"key":"f144","label":"Dummy Tank Qty before Month end Reco (KL)",            "type":"int",      "req":True,  "min":0,    "max":None,  "dec":0,    "opts":None,                              "hint":"Enter Total Qty for all Products as per SAP report (KL, whole number).", "sub":"Inventory Monitoring & Control",  "auto":None},
    {"no":145,"key":"f145","label":"Unrestricted Pipeline Qty",                            "type":"select",   "req":True,  "min":None, "max":None,  "dec":None, "opts":["Yes","No","NA"],                 "hint":"Select Yes if unrestricted pipeline quantity exists at location this month.",         "sub":"Inventory Monitoring & Control",  "auto":None},
    {"no":146,"key":"f146","label":"Reasons & Unrestricted Qty (KL)",                      "type":"textarea", "req":False, "min":None, "max":None,  "dec":None, "opts":None,  "show_when":{"f145":"Yes"}, "hint":"Enter reasons and unrestricted pipeline quantity in KL (max 750 chars). Visible only when Unrestricted Pipeline Qty = Yes.", "sub":"Inventory Monitoring & Control",  "auto":None},
    {"no":147,"key":"f147","label":"Slow Moving Stock >90 Days (KL)",                      "type":"number",   "req":True,  "min":0,    "max":None,  "dec":3,    "opts":None,                              "hint":"Enter quantity in KL (>=0). Slow moving stock held for more than 90 days.",          "sub":"Inventory Monitoring & Control",  "auto":None},
    {"no":25, "key":"f25",  "label":"Day End Report (TAS vs Gate vs SAP) – Reviewed & Signed by LIC","type":"select","req":True,"min":None,"max":None,"dec":None,"opts":["Yes","No","Non-TAS Location"],"hint":"Select appropriate option",                                                      "sub":"Inventory Monitoring & Control",  "auto":None},
    {"no":26, "key":"f26",  "label":"Auto-Reconciliation (% of Tanks on Auto Reco)",       "type":"number",   "req":True,  "min":0,    "max":100,   "dec":2,    "opts":None,                              "hint":"Auto Reco entries / Total Reco entries × 100",                                        "sub":"Inventory Monitoring & Control",  "auto":None},
    # Open SAP Transactions
    {"no":148,"key":"f148","label":"Open Sales Orders (Nos.)",                             "type":"int",      "req":True,  "min":0,    "max":None,  "dec":0,    "opts":None,                              "hint":"Enter count of open sales orders as per SAP at month end.",                           "sub":"Open SAP Transactions",           "auto":None},
    {"no":149,"key":"f149","label":"Open OBD's (Nos.)",                                    "type":"int",      "req":True,  "min":0,    "max":None,  "dec":0,    "opts":None,                              "hint":"Enter count of open Outbound Deliveries (OBDs) as per SAP at month end.",             "sub":"Open SAP Transactions",           "auto":None},
    {"no":150,"key":"f150","label":"Open DC's (Nos.)",                                     "type":"int",      "req":True,  "min":0,    "max":None,  "dec":0,    "opts":None,                              "hint":"Enter count of open Delivery Challans (DCs) as per SAP at month end.",               "sub":"Open SAP Transactions",           "auto":None},
    {"no":151,"key":"f151","label":"Open Shortages (KL)",                                  "type":"number",   "req":True,  "min":0,    "max":None,  "dec":3,    "opts":None,                              "hint":"Enter total open shortage quantity in KL as per SAP at month end.",                   "sub":"Open SAP Transactions",           "auto":None},
    # Manpower
    {"no":27,"key":"f27", "label":"Management",                                           "type":"int",      "req":True,  "min":0, "max":25,    "dec":0,  "opts":None,                         "hint":"Enter Management Manpower",                   "sub":"Manpower",                        "auto":None},
    {"no":28,"key":"f28", "label":"Non-Management",                                       "type":"int",      "req":True,  "min":0, "max":50,    "dec":0,  "opts":None,                         "hint":"Enter Non-Management Manpower",               "sub":"Manpower",                        "auto":None},
    {"no":29,"key":"f29", "label":"Contract Engineers",                                   "type":"int",      "req":True,  "min":0, "max":10,    "dec":0,  "opts":None,                         "hint":"Enter Contract Engineers deployed",            "sub":"Manpower",                        "auto":None},
    {"no":30,"key":"f30", "label":"GATs",                                                 "type":"int",      "req":True,  "min":0, "max":20,    "dec":0,  "opts":None,                         "hint":"Enter GATs deployed",                         "sub":"Manpower",                        "auto":None},
    {"no":31,"key":"f31", "label":"TATs",                                                 "type":"int",      "req":True,  "min":0, "max":20,    "dec":0,  "opts":None,                         "hint":"Enter TATs deployed",                         "sub":"Manpower",                        "auto":None},
    {"no":32,"key":"f32", "label":"Security Guards (Nos.)",                               "type":"int",      "req":True,  "min":0, "max":50,    "dec":0,  "opts":None,                         "hint":"As per Wages paid",                           "sub":"Manpower",                        "auto":None},
    {"no":33,"key":"f33", "label":"Electricians (Nos.)",                                  "type":"int",      "req":True,  "min":0, "max":20,    "dec":0,  "opts":None,                         "hint":"Electricians + Helpers deployed",             "sub":"Manpower",                        "auto":None},
    {"no":34,"key":"f34", "label":"Contract Labour (Nos.)",                               "type":"int",      "req":True,  "min":0, "max":150,   "dec":0,  "opts":None,                         "hint":"Enter Contract Workers deployed",             "sub":"Manpower",                        "auto":None},
    # Administrative
    {"no":141,"key":"f141","label":"E-diary observations recorded",                        "type":"int",      "req":True,  "min":1, "max":None,  "dec":0,  "opts":None,                         "hint":"Enter count of E-diary observations recorded","sub":"Administrative",                  "auto":None},
]

S2_FIELDS = [
    {"no":36, "key":"f36",  "label":"No. of Approved NPCB Projects",                      "type":"int",      "req":True,  "min":0, "max":None,  "dec":0,  "opts":None,                         "hint":"Whole numbers, max 2 digits",                 "sub":"Facilities & Planning",           "auto":None},
    {"no":37, "key":"f37",  "label":"Cumulative Value of Approved Projects (in Lacs)",    "type":"number",   "req":True,  "min":0, "max":None,  "dec":2,  "opts":None,                         "hint":"Enter Value in Lacs",                         "sub":"Facilities & Planning",           "auto":None},
    {"no":38, "key":"f38",  "label":"CAPEX (Lakhs)",                                       "type":"number",   "req":True,  "min":0, "max":None,  "dec":2,  "opts":None,                         "hint":"Enter Capex done in Lakhs",                   "sub":"Facilities & Planning",           "auto":None},
    {"no":39, "key":"f39",  "label":"Capex Target as per AOP (Lakhs)",                     "type":"number",   "req":True,  "min":0, "max":None,  "dec":2,  "opts":None,                         "hint":"Enter Capex Targets for FY",                  "sub":"Facilities & Planning",           "auto":None},
    {"no":40, "key":"f40",  "label":"CAPITALIZATION (Lakhs)",                              "type":"number",   "req":True,  "min":0, "max":None,  "dec":2,  "opts":None,                         "hint":"Capitalization done in the month",             "sub":"Facilities & Planning",           "auto":None},
    {"no":41, "key":"f41",  "label":"Capitalization Target as per AOP (Lakhs)",            "type":"number",   "req":True,  "min":0, "max":None,  "dec":2,  "opts":None,                         "hint":"Enter Capitalization Targets for FY",          "sub":"Facilities & Planning",           "auto":None},
    {"no":42, "key":"f42",  "label":"Scrap Value at Location (Rs in Lacs)",                "type":"number",   "req":True,  "min":0, "max":None,  "dec":2,  "opts":None,                         "hint":"Enter Expected Scrap Value",                  "sub":"Facilities & Planning",           "auto":None},
    {"no":43, "key":"f43",  "label":"Physical Scrap Disposal (Rs in Lacs)",                "type":"number",   "req":True,  "min":0, "max":None,  "dec":2,  "opts":None,                         "hint":"Scrap disposed value for the month",          "sub":"Facilities & Planning",           "auto":None},
    {"no":157,"key":"f157", "label":"Appropriation Done (Lakhs)",                          "type":"number",   "req":True,  "min":0, "max":None,  "dec":2,  "opts":None,                         "hint":"Enter value in Lakhs",                        "sub":"Facilities & Planning",           "auto":None},
    {"no":158,"key":"f158", "label":"Appropriation Target (Lakhs)",                        "type":"number",   "req":True,  "min":0, "max":None,  "dec":2,  "opts":None,                         "hint":"Enter value in Lakhs",                        "sub":"Facilities & Planning",           "auto":None},
]

S3_FIELDS = [
    {"no":44,"key":"f44", "label":"Rakes Unloaded / Loaded",                              "type":"int",      "req":True,  "min":0, "max":None,  "dec":0,  "opts":None,                         "hint":"Enter total Rakes handled",                   "sub":"S&D Data",                        "auto":None},
    {"no":45,"key":"f45", "label":"Pending Railway Claims – Uploaded in Google Sheet",    "type":"select",   "req":True,  "min":None,"max":None,"dec":None,"opts":["Yes","No","NA"],                 "hint":"Select appropriate option",                   "sub":"S&D Data",                        "auto":None},
    {"no":46,"key":"f46", "label":"MDP Qty Target (KL)",                                  "type":"number",   "req":True,  "min":0, "max":None,  "dec":3,  "opts":None,                         "hint":"Enter productwise values",                    "sub":"S&D Data",                        "auto":None},
    {"no":47,"key":"f47", "label":"MDP Qty Actual (KL)",                                  "type":"number",   "req":True,  "min":0, "max":None,  "dec":3,  "opts":None,                         "hint":"Enter productwise values",                    "sub":"S&D Data",                        "auto":None},
    {"no":48,"key":"f48", "label":"OMC MDP Target (KL)",                                  "type":"number",   "req":True,  "min":0, "max":None,  "dec":3,  "opts":None,                         "hint":"Enter productwise values",                    "sub":"S&D Data",                        "auto":None},
    {"no":49,"key":"f49", "label":"OMC MDP Actual (KL)",                                  "type":"number",   "req":True,  "min":0, "max":None,  "dec":3,  "opts":None,                         "hint":"Enter productwise values",                    "sub":"S&D Data",                        "auto":None},
]

S4_FIELDS = [
    {"no":50,"key":"f50", "label":"EBP – Ethanol Blending Percentage",                    "type":"number",   "req":True,  "min":0, "max":100,   "dec":2,  "opts":None,                         "hint":"Enter EBP % for the month",                  "sub":"Biofuel Data",                    "auto":None},
    {"no":51,"key":"f51", "label":"Unblended MS Retail Sales (KL)",                       "type":"number",   "req":True,  "min":0, "max":None,  "dec":3,  "opts":None,                         "hint":"Enter value in KL",                           "sub":"Biofuel Data",                    "auto":None},
    {"no":52,"key":"f52", "label":"Biodiesel Receipt Qty (KL)",                           "type":"number",   "req":True,  "min":0, "max":None,  "dec":3,  "opts":None,                         "hint":"Enter value in KL",                           "sub":"Biofuel Data",                    "auto":None},
    {"no":53,"key":"f53", "label":"Biodiesel Blending Percentage",                        "type":"number",   "req":True,  "min":0, "max":100,   "dec":2,  "opts":None,                         "hint":"Enter Blending % for the month",              "sub":"Biofuel Data",                    "auto":None},
]

S5_FIELDS = [
    {"no":54,"key":"f54", "label":"M&I Index (internal-half yearly)",                       "type":"number",   "req":False, "min":0, "max":100,   "dec":2,  "opts":None, "hint":"Half-yearly index (Apr-Sep / Oct-Mar). Enter value 0-100 or leave blank if not due this month — system allows submission with blank for months where this was already filled earlier in the half-year.",  "sub":"M&I Data", "auto":None},
    {"no":55,"key":"f55", "label":"PM Percentage",                                          "type":"number",   "req":True,  "min":0, "max":100,   "dec":2,  "opts":None, "hint":"Enter PM %",                           "sub":"M&I Data", "auto":None},
    {"no":56,"key":"f56", "label":"Breakdown Equipment Details",                            "type":"textarea", "req":False, "min":None,"max":None,"dec":None,"opts":None, "hint":"Enter equipment breakdown details: equipment name, nature of breakdown, date it occurred, and current status. e.g. Pump-2 (MS): Bearing failure on 05/06/2026, under repair. Leave blank if no breakdown this month.", "sub":"M&I Data", "auto":None},
    {"no":57,"key":"f57", "label":"Tank Cleaned (Tank#, Product, Capacity & Date)",        "type":"textarea", "req":False, "min":None,"max":None,"dec":None,"opts":None, "hint":"Enter details of tanks cleaned this month: Tank No., Product, Capacity (KL), and date of cleaning. e.g. TK-136 (MS, 5000 KL) cleaned on 10/06/2026. Leave blank if no tank cleaning this month.", "sub":"M&I Data", "auto":None},
    {"no":58,"key":"f58", "label":"Tank Cleaning Extensions (eFN# & date till extension)", "type":"textarea", "req":False, "min":None,"max":None,"dec":None,"opts":None, "hint":"Enter details (max 750 chars)",         "sub":"M&I Data", "auto":None},
]

S6_FIELDS = [
    # HSE Performance
    {"no":59, "key":"f59",  "label":"HSE Index vs Target",                                  "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter HSE Index as a percentage",             "sub":"HSE Performance",                 "auto":None},
    {"no":60, "key":"f60",  "label":"Water Consumed in Month (KL)",                         "type":"number",   "req":True,  "min":0,  "max":None, "dec":3,  "opts":None,                         "hint":"Enter values in KL as per Meter Reading",     "sub":"HSE Performance",                 "auto":None},
    {"no":61, "key":"f61",  "label":"SWC (KL/MT)",                                          "type":"number",   "req":False, "min":0,  "max":None, "dec":3,  "opts":None,                         "hint":"Auto Calculated = Water Consumed / Thruput",  "sub":"HSE Performance",                 "auto":"f60/f3"},
    {"no":62, "key":"f62",  "label":"No. of TT Accidents",                                  "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter TT Accidents occurred in Month",        "sub":"HSE Performance",                 "auto":None},
    {"no":63, "key":"f63",  "label":"No. of Fatalities",                                    "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter Fatalities due to accidents in month",  "sub":"HSE Performance",                 "auto":None},
    {"no":64, "key":"f64",  "label":"No. of Near Miss / UA / UC Reported",                  "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter Near Miss / UA / UC count",             "sub":"HSE Performance",                 "auto":None},
    {"no":65, "key":"f65",  "label":"No. of Permits Issued",                                "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter Permit Issued Count",                   "sub":"HSE Performance",                 "auto":None},
    {"no":66, "key":"f66",  "label":"No. of MOC's Created and Approved",                   "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter MOC approved Count",                    "sub":"HSE Performance",                 "auto":None},
    {"no":67, "key":"f67",  "label":"Pending MDSA Observations vs Total (%)",               "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Pending MDSA obs / Total obs × 100",          "sub":"HSE Performance",                 "auto":None},
    {"no":68, "key":"f68",  "label":"Pending OISD Observations vs Total (%)",               "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Pending OISD obs / Total obs × 100",          "sub":"HSE Performance",                 "auto":None},
    # Safety Compliance
    {"no":69, "key":"f69",  "label":"OISD Observations > 1 Year",                          "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Count of OISD observations older than 1 year","sub":"Safety Compliance",               "auto":None},
    {"no":70, "key":"f70",  "label":"All SOPs Generated & Re-validated (Date < 3 Years)",  "type":"select",   "req":True,  "min":None,"max":None,"dec":None,"opts":["Yes","No","NA"],                 "hint":"Select appropriate option",                   "sub":"Safety Compliance",               "auto":None},
    {"no":71, "key":"f71",  "label":"Green Belt Area (in SQM)",                             "type":"number",   "req":True,  "min":0,  "max":None, "dec":2,  "opts":None,                         "hint":"Enter Green Belt area in square metres",      "sub":"Safety Compliance",               "auto":None},
    # CCTV & Security
    {"no":72, "key":"f72",  "label":"No. of CCTV Installed",                                "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter total count of CCTV installed",         "sub":"CCTV & Security",                 "auto":None},
    {"no":73, "key":"f73",  "label":"CCTV Not Functional",                                  "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter Non-functional CCTV count",             "sub":"CCTV & Security",                 "auto":None},
    {"no":74, "key":"f74",  "label":"% CCTV Breakdown",                                     "type":"number",   "req":False, "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Auto Calculated = Not Functional / Total × 100","sub":"CCTV & Security",              "auto":"f73/f72*100"},
    {"no":75, "key":"f75",  "label":"VA Exception %",                                       "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter data as per VA portal",                 "sub":"CCTV & Security",                 "auto":None},
    # Awards
    {"no":76, "key":"f76",  "label":"Awards Received (Details)",                            "type":"textarea", "req":False, "min":None,"max":None,"dec":None,"opts":None,                        "hint":"Enter details of awards received this month: award name, awarding authority, and date received. e.g. Best Safety Performance Award by HPCL HQ on 15/06/2026. Leave blank if no awards received.",  "sub":"Awards",                          "auto":None},
]

S7_FIELDS = [
    # Bay Operations
    {"no":77,  "key":"f77",  "label":"No. of Bays at Location",                             "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter total number of loading bays",          "sub":"Bay Operations",                  "auto":None},
    {"no":78,  "key":"f78",  "label":"No. of Functional Bays at Location",                  "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of functional bays",              "sub":"Bay Operations",                  "auto":None},
    {"no":79,  "key":"f79",  "label":"OLA %",                                               "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter OLA % as per IMS Reports",              "sub":"Bay Operations",                  "auto":None},
    {"no":80,  "key":"f80",  "label":"COLA %",                                              "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter COLA % as per IMS Reports",             "sub":"Bay Operations",                  "auto":None},
    {"no":81,  "key":"f81",  "label":"AUTO DC %",                                           "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter AUTO DC % as per IMS Reports",          "sub":"Bay Operations",                  "auto":None},
    {"no":82,  "key":"f82",  "label":"CAT-A %",                                             "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter CAT-A % as per IMS Reports",            "sub":"Bay Operations",                  "auto":None},
    {"no":83,  "key":"f83",  "label":"LPM",                                                 "type":"number",   "req":True,  "min":0,  "max":None, "dec":2,  "opts":None,                         "hint":"Enter LPM as per TAS Reports",                "sub":"Bay Operations",                  "auto":None},
    {"no":152, "key":"f152", "label":"Bay Occupancy (%)",                                  "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter Bay Occupancy % for the month as per TAS report. e.g. total occupied bay-hours / total available bay-hours × 100.", "sub":"Bay Operations",                  "auto":None},
    # TAS Performance
    {"no":84,  "key":"f84",  "label":"Operating Hours of Location",                         "type":"int",      "req":True,  "min":0,  "max":744,  "dec":0,  "opts":None,                         "hint":"Enter operating hours in month (max 744)",    "sub":"TAS Performance",                 "auto":None},
    {"no":85,  "key":"f85",  "label":"Indents Executed within Operational Hours",           "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count as per TAS Reports",              "sub":"TAS Performance",                 "auto":None},
    {"no":86,  "key":"f86",  "label":"Indents Executed beyond Operational Hours",           "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count as per TAS Reports",              "sub":"TAS Performance",                 "auto":None},
    {"no":87,  "key":"f87",  "label":"% Indents beyond Operational Hours",                  "type":"number",   "req":False, "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Auto Calculated = Beyond / (Within + Beyond) × 100","sub":"TAS Performance",           "auto":"f86*100/(f86+f85)"},
    {"no":88,  "key":"f88",  "label":"TFMS vs SAP Performance (%)",                         "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter % as per SAP Reports",                  "sub":"TAS Performance",                 "auto":None},
    {"no":89,  "key":"f89",  "label":"File Note No. & Date for TFMS–SAP Integration",      "type":"textarea", "req":False, "min":None,"max":None,"dec":None,"opts":None,                        "hint":"Enter File Note number and date raised for TFMS–SAP integration. e.g. FN-2026/06/123 dated 01/06/2026 — Discrepancy of 10 KL in MS loading. Leave blank if no file note raised this month.", "sub":"TAS Performance",                 "auto":None},
    {"no":90,  "key":"f90",  "label":"First 2 Hours TT Released per Bay (Operational Bays)","type":"number",  "req":True,  "min":0,  "max":None, "dec":2,  "opts":None,                         "hint":"Enter value as per TAS Reports",              "sub":"TAS Performance",                 "auto":None},
    {"no":91,  "key":"f91",  "label":"Online Density % (Target 98%)",                       "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter % as per TAS Reports",                  "sub":"TAS Performance",                 "auto":None},
    {"no":153, "key":"f153", "label":"Instances of Manual Density Forced (Nos.)",          "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of manual density forced instances for the month as per TAS report.", "sub":"TAS Performance",                 "auto":None},
    {"no":92,  "key":"f92",  "label":"No. of PLC IO's Forced",                              "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count as per TAS Reports",              "sub":"TAS Performance",                 "auto":None},
    {"no":93,  "key":"f93",  "label":"No. of Manual Bay Allocations",                       "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count as per TAS Reports",              "sub":"TAS Performance",                 "auto":None},
    {"no":94,  "key":"f94",  "label":"No. of Sick TT Instances",                            "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count as per TAS Reports",              "sub":"TAS Performance",                 "auto":None},
    {"no":95,  "key":"f95",  "label":"No. of Cancelled TT's",                              "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count as per TAS Reports",              "sub":"TAS Performance",                 "auto":None},
    {"no":96,  "key":"f96",  "label":"No. of TT's Loaded Locally",                         "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count as per TAS Reports",              "sub":"TAS Performance",                 "auto":None},
    {"no":97,  "key":"f97",  "label":"Quantity of Local Loading (KL)",                      "type":"number",   "req":True,  "min":0,  "max":None, "dec":3,  "opts":None,                         "hint":"Enter value in KL",                           "sub":"TAS Performance",                 "auto":None},
    {"no":98,  "key":"f98",  "label":"Cycle Time R2 to R3 (Min)",                           "type":"number",   "req":True,  "min":0,  "max":None, "dec":2,  "opts":None,                         "hint":"Enter average cycle time in minutes",         "sub":"TAS Performance",                 "auto":None},
    {"no":154, "key":"f154", "label":"R2 - Loading Start Time (Minutes)",                  "type":"number",   "req":True,  "min":0,  "max":None, "dec":2,  "opts":None,                         "hint":"Enter avg. value for the month as per TAS report — time from R2 gate entry to loading start (minutes).", "sub":"TAS Performance",                 "auto":None},
    {"no":155, "key":"f155", "label":"Loading Completed to R3 Time (Minutes)",             "type":"number",   "req":True,  "min":0,  "max":None, "dec":2,  "opts":None,                         "hint":"Enter avg. value for the month as per TAS report — time from loading completion to R3 gate exit (minutes).", "sub":"TAS Performance",                 "auto":None},
    {"no":99,  "key":"f99",  "label":"TAS Open Audit Observations vs Total (%)",            "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter % of open audit observations",          "sub":"TAS Performance",                 "auto":None},
    # System Compliance
    {"no":100, "key":"f100", "label":"BCU vs MFM Totalizer Matching",                       "type":"select",   "req":True,  "min":None,"max":None,"dec":None,"opts":["Yes","No","NA"],                "hint":"Select appropriate option",                   "sub":"System Compliance",               "auto":None},
    {"no":156, "key":"f156", "label":"Reasons - BCU-MFM not matching",                    "type":"textarea", "req":False, "min":None,"max":None,"dec":None,"opts":None, "show_when":{"f100":"No"}, "hint":"Enter reasons for BCU vs MFM Totalizer mismatch (max 750 chars). Include date, product, quantity variance and corrective action. Visible only when BCU vs MFM = No.", "sub":"System Compliance",               "auto":None},
    {"no":101, "key":"f101", "label":"No. of Instances of Unauthorized Flow",               "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter whole number count",                    "sub":"System Compliance",               "auto":None},
    {"no":102, "key":"f102", "label":"User Access as per Circular",                         "type":"select",   "req":True,  "min":None,"max":None,"dec":None,"opts":["Yes","No","NA"],                "hint":"Select appropriate option",                   "sub":"System Compliance",               "auto":None},
    {"no":103, "key":"f103", "label":"H, HH, HHH Matching with File Note",                  "type":"select",   "req":True,  "min":None,"max":None,"dec":None,"opts":["Yes","No","NA"],                "hint":"Select appropriate option",                   "sub":"System Compliance",               "auto":None},
    {"no":104, "key":"f104", "label":"TT Dip Check %",                                      "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter % as per SAP Reports",                  "sub":"System Compliance",               "auto":None},
]

S8_FIELDS = [
    {"no":105, "key":"f105", "label":"EM Locks Spare Inventory",                            "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count as per System Report",            "sub":"EM Lock Data",                    "auto":None},
    {"no":106, "key":"f106", "label":"EM Lock Spare Key Inventory",                         "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count as per System Report",            "sub":"EM Lock Data",                    "auto":None},
    {"no":107, "key":"f107", "label":"Dormant EM Locks",                                    "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count as per System Report",            "sub":"EM Lock Data",                    "auto":None},
    {"no":108, "key":"f108", "label":"Dormant Keys",                                        "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count as per System Report",            "sub":"EM Lock Data",                    "auto":None},
    {"no":109, "key":"f109", "label":"EM Lock Exception % — TT Outside RO Radius",         "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter % as per System Report",                "sub":"EM Lock Data",                    "auto":None},
]

S9_FIELDS = [
    # TT Fleet
    {"no":110, "key":"f110", "label":"Total TTs Operating at Location",                     "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter total TT count at location",            "sub":"TT Fleet",                        "auto":None},
    {"no":111, "key":"f111", "label":"EC Approved TT Numbers",                              "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter EC Approved TT count",                  "sub":"TT Fleet",                        "auto":None},
    {"no":112, "key":"f112", "label":"DCT TTs < 18 KL",                                     "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of DCT TTs below 18 KL",          "sub":"TT Fleet",                        "auto":None},
    {"no":113, "key":"f113", "label":"DCT TTs 18–24 KL",                                    "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of DCT TTs 18 KL to 24 KL",       "sub":"TT Fleet",                        "auto":None},
    {"no":114, "key":"f114", "label":"DCT TTs >= 25 KL",                                    "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of DCT TTs 25 KL and above",      "sub":"TT Fleet",                        "auto":None},
    {"no":115, "key":"f115", "label":"TPT TTs < 18 KL",                                     "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of TPT TTs below 18 KL",          "sub":"TT Fleet",                        "auto":None},
    {"no":116, "key":"f116", "label":"TPT TTs 18–24 KL",                                    "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of TPT TTs 18 KL to 24 KL",       "sub":"TT Fleet",                        "auto":None},
    {"no":117, "key":"f117", "label":"TPT TTs >= 25 KL",                                    "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of TPT TTs 25 KL and above",      "sub":"TT Fleet",                        "auto":None},
    {"no":118, "key":"f118", "label":"Bottom Loading TTs < 18 KL",                          "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of BL TTs below 18 KL",           "sub":"TT Fleet",                        "auto":None},
    {"no":119, "key":"f119", "label":"Bottom Loading TTs 18–24 KL",                         "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of BL TTs 18 KL to 24 KL",        "sub":"TT Fleet",                        "auto":None},
    {"no":120, "key":"f120", "label":"Bottom Loading TTs >= 25 KL",                         "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of BL TTs 25 KL and above",       "sub":"TT Fleet",                        "auto":None},
    {"no":121, "key":"f121", "label":"Non-Reporting TTs > 15 Days",                         "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"TTs not reporting for more than 15 days",     "sub":"TT Fleet",                        "auto":None},
    # TT Shortages & Violations
    {"no":122, "key":"f122", "label":"No. of TT Shortages Reported",                        "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter shortage case count for the month",     "sub":"TT Shortages & Violations",       "auto":None},
    {"no":123, "key":"f123", "label":"Cumulative TT Shortages for Month (KL)",              "type":"number",   "req":True,  "min":0,  "max":None, "dec":3,  "opts":None,                         "hint":"Enter cumulative shortage quantity in KL",    "sub":"TT Shortages & Violations",       "auto":None},
    {"no":124, "key":"f124", "label":"No. of Abnormal TT Shortage Cases Investigated",      "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of investigated cases",           "sub":"TT Shortages & Violations",       "auto":None},
    {"no":125, "key":"f125", "label":"No. of SCN Issued",                                   "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of SCNs issued in month",         "sub":"TT Shortages & Violations",       "auto":None},
    {"no":126, "key":"f126", "label":"No. of Actions Taken (Blacklisting / Termination)",  "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of blacklisting/termination actions","sub":"TT Shortages & Violations",    "auto":None},
    {"no":127, "key":"f127", "label":"Pending TT Conversion to BL (Nos)",                  "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of TTs pending BL conversion",   "sub":"TT Shortages & Violations",       "auto":None},
    {"no":128, "key":"f128", "label":"Speed Violation %",                                   "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter % as per System Report",                "sub":"TT Shortages & Violations",       "auto":None},
    {"no":129, "key":"f129", "label":"Route Violations %",                                  "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter % as per System Report",                "sub":"TT Shortages & Violations",       "auto":None},
    {"no":130, "key":"f130", "label":"% Routes Corrected",                                  "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter % of routes corrected in month",        "sub":"TT Shortages & Violations",       "auto":None},
    {"no":131, "key":"f131", "label":"Pending Toll Amount to be Approved (Rs)",             "type":"number",   "req":True,  "min":0,  "max":None, "dec":2,  "opts":None,                         "hint":"Enter pending toll amount in Rupees",         "sub":"TT Shortages & Violations",       "auto":None},
    {"no":132, "key":"f132", "label":"Driver Ranking Maintained",                           "type":"select",   "req":True,  "min":None,"max":None,"dec":None,"opts":["Yes","No","NA"],                "hint":"Select appropriate option",                   "sub":"TT Shortages & Violations",       "auto":None},
    {"no":133, "key":"f133", "label":"TPI Inspection Part-A",                               "type":"int",      "req":True,  "min":0,   "max":None, "dec":0,  "opts":None,                        "hint":"Enter No. of TT's Inspected in Month",        "sub":"TT Shortages & Violations",       "auto":None},
    {"no":134, "key":"f134", "label":"TPI Inspection Part-B",                               "type":"int",      "req":True,  "min":0,   "max":None, "dec":0,  "opts":None,                        "hint":"Enter No. of TT's Inspected in Month",        "sub":"TT Shortages & Violations",       "auto":None},
    {"no":135, "key":"f135", "label":"EOI Tender Finalization Status",                      "type":"textarea", "req":False, "min":None,"max":None,"dec":None,"opts":None,                        "hint":"Enter current status of EOI tender finalization — include stage reached, date of last action, and any pending steps. e.g. L1 identified on 10/06/2026, awaiting HQ approval. (max 750 chars)", "sub":"TT Shortages & Violations", "auto":None},
    {"no":136, "key":"f136", "label":"Freight Amount Recovered for Month (Rs)",             "type":"number",   "req":True,  "min":0,  "max":None, "dec":2,  "opts":None,                         "hint":"Enter amount recovered in Rupees",            "sub":"TT Shortages & Violations",       "auto":None},
    {"no":137, "key":"f137", "label":"Total TDG Violations (% of Total Trips)",             "type":"number",   "req":True,  "min":0,  "max":100,  "dec":2,  "opts":None,                         "hint":"Enter TDG Violation % as per VTS Portal",    "sub":"TT Shortages & Violations",       "auto":None},
]

S10_FIELDS = [
    {"no":138, "key":"f138", "label":"Idea Submissions (Nos)",                              "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter number of ideas submitted",             "sub":"Others",                          "auto":None},
    {"no":139, "key":"f139", "label":"IRR's (if any)",                                      "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of IRRs",                         "sub":"Others",                          "auto":None},
    {"no":140, "key":"f140", "label":"Legal Cases",                                         "type":"int",      "req":True,  "min":0,  "max":None, "dec":0,  "opts":None,                         "hint":"Enter count of legal cases",                  "sub":"Others",                          "auto":None},
]

SECTION_FIELDS: dict[int, list] = {
    1: S1_FIELDS,
    2: S2_FIELDS,
    3: S3_FIELDS,
    4: S4_FIELDS,
    5: S5_FIELDS,
    6: S6_FIELDS,
    7: S7_FIELDS,
    8: S8_FIELDS,
    9: S9_FIELDS,
    10: S10_FIELDS,
}

SECTION_NAMES: dict[int, str] = {
    1:  "S1 — Operations",
    2:  "S2 — Facilities & Planning (F&P)",
    3:  "S3 — Supply & Distribution (S&D)",
    4:  "S4 — Biofuel",
    5:  "S5 — Maintenance & Inspection (M&I)",
    6:  "S6 — Health, Safety & Environment (HSE)",
    7:  "S7 — Operational Efficiency & TAS",
    8:  "S8 — EM Lock Performance",
    9:  "S9 — Transportation",
    10: "S10 — Others",
}

# ── Location-type field applicability ─────────────────────────────────────────
# Fields marked N in TOP Data.xlsx for TOP/Jamnagar locations
TOP_EXCLUDED_FIELDS: frozenset = frozenset({
    # S1 — Solar (no solar plant at TOPs)
    "f9", "f10", "f11",
    # S1 — Electricity (not applicable at TOPs)
    "f12", "f13", "f14", "f15", "f16", "f17", "f18", "f19", "f20", "f21",
    # S1 — Inventory
    "f24", "f26",
    # S1 — Manpower
    "f30", "f31", "f32", "f33", "f141",
    # S2 — Facilities & Planning (entire section N/A)
    "f35", "f36", "f37", "f38", "f39", "f40", "f41", "f42", "f43",
    "f157", "f158",
    # S5 — M&I summary (entire section N/A; S5A also skipped)
    "f54", "f55", "f56", "f57", "f58",
    # S6 — HSE (partial)
    "f59", "f60", "f61", "f65", "f67", "f68", "f69", "f71",
    "f72", "f73", "f74", "f75", "f76",
    # S7 — TAS (partial)
    "f77", "f78", "f83", "f152", "f88", "f89", "f90", "f91", "f92", "f93",
    "f153", "f154", "f155",
    "f96", "f97", "f98", "f99", "f100", "f101", "f102", "f103", "f104", "f156",
})

# Fields marked N in TOP Data.xlsx for HMEL locations
HMEL_EXCLUDED_FIELDS: frozenset = frozenset({
    # S1 — Solar
    "f9", "f10", "f11",
    # S1 — Inventory
    "f24", "f26",
    # S2 — Facilities & Planning (entire section N/A)
    "f35", "f36", "f37", "f38", "f39", "f40", "f41", "f42", "f43",
    "f157", "f158",
    # S5 — M&I summary (entire section N/A; S5A also skipped)
    "f54", "f55", "f56", "f57", "f58",
    # S6 — HSE (partial)
    "f59", "f67", "f68", "f69", "f71",
    "f72", "f73", "f74", "f75", "f76",
    # S7 — TAS (partial)
    "f77", "f78", "f83", "f152", "f88", "f89", "f90", "f91", "f92", "f93",
    "f153", "f154", "f155",
    "f96", "f97", "f98", "f99", "f100", "f101", "f102", "f103", "f104", "f156",
})

# Sections entirely N/A for a loc_type — auto-completed, not shown to user
TOP_SKIP_SECTIONS: frozenset = frozenset({2, 5})   # S2 F&P, S5 M&I
HMEL_SKIP_SECTIONS: frozenset = frozenset({2, 5})  # same

def get_excluded_fields(loc_type: str) -> frozenset:
    """Return set of field keys not applicable for this location type."""
    if loc_type == "TOP":
        return TOP_EXCLUDED_FIELDS
    if loc_type == "HMEL":
        return HMEL_EXCLUDED_FIELDS
    return frozenset()  # HPCL — all fields applicable

def get_skip_sections(loc_type: str) -> frozenset:
    """Return section numbers to skip entirely for this location type."""
    if loc_type == "TOP":
        return TOP_SKIP_SECTIONS
    if loc_type == "HMEL":
        return HMEL_SKIP_SECTIONS
    return frozenset()
